FORMAT: 1A

# Dredd: Test Two

Hello WORLD!

## My Resource [/r]
### Retrieve [GET]
- response 200 (application/json; charset=utf-8)
    - attributes
        - message: hello worl color!


### Create [POST]
- response 201 (application/json)

        { "message": "color" }
