FORMAT: 1A

# Dredd: Test Two
This is a production version.

## My Resource [/r]
### Retrieve [GET]
- response 200 (application/json; charset=utf-8)
    - attributes
        - message: hello world!


### Create [POST]
- response 201 (application/json)

        { "message": "color" }